### ISSUE TITLE
Bug when a user doesn't exist anymore

### ISSUE THREAD

**Issue by weierophinney** [mezzio/mezzio-authentication-session#1]
There is a problem with the user factory closure:

https://github.com/zendframework/zend-expressive-authentication-session/blob/93ba0968a4118bc1800a43e93fbfd6ef79ac12d9/src/PhpSession.php#L63-L69

When a user doesn't exist anymore in the repository, the user factory should be able to return `null`. Right now a`TypeError` is thrown.

---

Originally posted by @thomasvargiu at https://github.com/zendframework/zend-expressive-authentication-session/issues/23

**Comment by alexmerlin** [comment]
Closing issue due to being inactive for more than 1 year.
