### ISSUE TITLE
Documentation:  LoginHandler getRedirect() return type

### ISSUE THREAD

**Issue by sheridans** [mezzio/mezzio-authentication-session#17]
Slight bug in the documentation for the LoginHandler example, specifically with the `getRedirect()` function. There is a chance of returning the Uri object instead of a string. 

The final return statement `return $redirect;` should be cast to string,`return (string)$redirect;` to ensure a string is returned and not the actual Uri object.

**Comment by froschdesign** [comment]
@sheridans 
Thanks for reporting the problem.
If you could create a pull request, that would be great! 👍 

Please also have a look at this suggestion for an alternative workflow: #2

**Comment by sheridans** [comment]
Thanks I've created a PR for this, are we planning on having this alternative workflow in docs? I can take at updating them if so?
